### ISSUE TITLE
食事について

### ISSUE THREAD

**Issue by kurohune538** [designcat/asobousai#10]
画像：https://drive.google.com/open?id=0B_W3t7fN7MFEWFF0cHBrWWNOUUU
名称：「えんの海丼」
提供：NanZ Kitchen　http://nanz.villageinc.jp/archives/52
価格：（ランチメニュー）
備考：「第一回下田ブランド」認定

をイベント・ブースの下に

**Comment by kurohune538** [comment]
![image](https://cloud.githubusercontent.com/assets/8509325/17837456/7f3337d2-67ee-11e6-8fed-b5b83b2daea5.png)
改行がされてない
@0426yuki

**Comment by 0426yuki** [comment]
本当だ

**Comment by 0426yuki** [comment]
修正済
