### ISSUE TITLE
詳しいイベント概要を見るのリンク範囲が１行全部になってしまっている

### ISSUE THREAD

**Issue by kurohune538** [designcat/asobousai#2]
![image](https://cloud.githubusercontent.com/assets/8509325/17767190/ea23406e-6569-11e6-895e-fc7920b47455.png)

**Comment by 0426yuki** [comment]
aタグの位置変更済

**Comment by kurohune538** [comment]
イベントの方直ってないよ！

**Comment by 0426yuki** [comment]
なおしましまたー！
